- hosts: all

  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/global.yml

  tasks:
    - name: add samtools
      include: tasks/samtools.yml
      tags: samtools
      loop:
        - 1.15.1
        - 1.14
        - 1.13
        - 1.12
        - 1.11
      loop_control:
        loop_var: version


    - name: add htslib
      include: tasks/htslib.yml
      tags: htslib
      loop:
        - 1.15.1
        - 1.14
        - 1.13
        - 1.12
        - 1.11
      loop_control:
        loop_var: version


    - name: add bcftools
      include: tasks/bcftools.yml
      tags: bcftools
      loop:
        - 1.14
        - 1.13
        - 1.12
        - 1.11
      loop_control:
        loop_var: version

    - name: add vcftools
      include: tasks/vcftools.yml
      tags: vcftools
      loop:
        - 1.16
      loop_control:
        loop_var: version


    - name: add bwa
      include: tasks/bwa.yml
      tags: bwa
      loop:
        - 0.7.17
      loop_control:
        loop_var: version

    - name: add minimap2
      include: tasks/minimap2.yml
      tags: minimap2
      loop:
        - "2.20"
        - 2.21
        - 2.22
      loop_control:
        loop_var: version

    - name: add star
      include: tasks/star.yml
      tags: star
      loop:
        - "2.7.8a"
      loop_control:
        loop_var: version

    - name: add bedtools
      include: tasks/bedtools.yml
      tags: bedtools
      loop:
        - "2.30.0"
      loop_control:
        loop_var: version

    - name: add salmon
      include: tasks/salmon.yml
      tags: salmon
      loop:
        - "1.5.2"
      loop_control:
        loop_var: version

    - name: add subread
      include: tasks/subread.yml
      tags: subread
      loop:
        - "2.0.3"
      loop_control:
        loop_var: version

    - name: add gatk
      include: tasks/gatk.yml
      tags: gatk
      loop:
        - "4.2.0.0"
      loop_control:
        loop_var: version

    - name: add picard
      include: tasks/picard.yml
      tags: picard
      loop:
        - "2.26.4"
      loop_control:
        loop_var: version

    - name: add igv
      include: tasks/igv.yml
      tags: igv
      loop:
        - "2.11"
      loop_control:
        loop_var: version

    - name: add cellranger (only latest is available for download, but for now...)
      include: tasks/cellranger.yml
      tags: cellranger
      loop:
        - "6.1.1"
      loop_control:
        loop_var: version


    - name: add hisat2
      include: tasks/hisat2.yml
      tags: hisat2
      loop:
        # This is a fudge, as there is no logical version download link       
        - "2.2.1"
      loop_control:
        loop_var: version


    - name: add macs2
      include: tasks/macs2.yml
      tags: macs2
      loop:
        - "2.2.7.1"
      loop_control:
        loop_var: version


    - name: add fastqc
      include: tasks/fastqc.yml
      tags: fastqc
      loop:
        - "0.11.9"
      loop_control:
        loop_var: version

    - name: add kentUtils
      include: tasks/kentUtils.yml
      tags: kentUtils
      loop:
        - "431"
      loop_control:
        loop_var: version


    - name: add bedops
      include: tasks/bedops.yml
      tags: bedops
      loop:
        - "2.4.40"
        - "2.4.35"
      loop_control:
        loop_var: version
