- hosts: all

  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/global.yml

  tasks:
    - name: add samtools
      include: tasks/samtools.yml
      tags: samtools
      loop:
        - 1.13
        - 1.12
        - 1.11
      loop_control:
        loop_var: version


    - name: add htslib
      include: tasks/htslib.yml
      tags: htslib
      loop:
        - 1.13
        - 1.12
        - 1.11
      loop_control:
        loop_var: version


    - name: add bcftools
      include: tasks/bcftools.yml
      tags: bcftools
      loop:
        - 1.13
        - 1.12
        - 1.11
      loop_control:
        loop_var: version

    - name: add bwa
      include: tasks/bwa.yml
      tags: bwa
      loop:
        - 0.7.17
      loop_control:
        loop_var: version

    - name: add minimap2
      include: tasks/minimap2.yml
      tags: minimap2
      loop:
        - "2.20"
        - 2.21
        - 2.22
      loop_control:
        loop_var: version

    - name: add star
      include: tasks/star.yml
      tags: star
      loop:
        - "2.7.8a"
      loop_control:
        loop_var: version

    - name: add bedtools
      include: tasks/bedtools.yml
      tags: bedtools
      loop:
        - "2.30.0"
      loop_control:
        loop_var: version

    - name: add salmon
      include: tasks/salmon.yml
      tags: salmon
      loop:
        - "1.5.1"
      loop_control:
        loop_var: version

    - name: add subread
      include: tasks/subread.yml
      tags: subread
      loop:
        - "2.0.3"
      loop_control:
        loop_var: version
