---
- name: install hisat2
  block:

    - name: set version
      set_fact:
        version: 2.2.1


    - name: check if hisat2 executable is present
      shell: "which {{software_dir}}/hisat2/{{version}}/bin/hisat2"
      register: hisat2_bin
      ignore_errors: true

    - name: make dir for hisat2
      ansible.builtin.file:
        path: "{{software_dir}}/hisat2/{{version}}/bin"
        state: directory
        mode: '0755'        

    - name: Install hisat2
      ansible.builtin.shell:  |
        curl -Lo  /tmp/hisat2.zip https://cloud.biohpc.swmed.edu/index.php/s/oTtGWbWjaxsQ2Ho/download 
        mkdir /tmp/hisat
        unzip /tmp/hisat2.zip -d /tmp/hisat2 
        cp /tmp/hisat2/*/hisat2* {{software_dir}}/hisat2/{{version}}/bin/
        rm -rf /tmp/hisat*
      when: hisat_bin.rc != 0


    - name: make modulesfile dir for hisat
      ansible.builtin.file:
        path: "{{modulefiles_dir}}/hisat2/"
        state: directory
        mode: '0755'        

    - name: write module file
      template: 
        src: templates/modules/hisat2.j2
        dest: "{{modulefiles_dir}}/hisat2/{{version}}"
        

        



        