---
- name: install salmon
  block:

    - name: check if salmon executable is present
      shell: "which {{software_dir}}/salmon/{{version}}/bin/salmon"
      register: salmon_bin
      ignore_errors: true

    - name: make dir for salmon
      ansible.builtin.file:
        path: "{{software_dir}}/salmon/{{version}}"
        state: directory
        mode: '0755'        


    - name: Install salmon
      ansible.builtin.shell:  |
        curl -Lo /tmp/salmon.tgz https://github.com/COMBINE-lab/salmon/releases/download/v{{version}}/salmon-{{version}}_linux_x86_64.tar.gz
        tar zxvf /tmp/salmon.tgz --strip 1 -C  {{software_dir}}/salmon/{{version}}
        rm -f /tmp/salmon.tgz
      when: False and salmon_bin.rc != 0


    - name: Build and install salmon
      ansible.builtin.shell:  |
        curl -Lo /tmp/salmon.tgz https://github.com/COMBINE-lab/salmon/archive/refs/tags/v{{version}}.tar.gz
        mkdir -p /tmp/salmon/build
        tar zxvf /tmp/salmon.tgz --strip 1 -C /tmp/salmon 
        cd /tmp/salmon/build
        cmake -DCMAKE_PREFIX_PATH={{software_dir}}/salmon/{{version}}
        make  
        make install  
        rm -rf /tmp/salmon*

        tar zxvf /tmp/salmon.tgz --strip 1 -C  {{software_dir}}/salmon/{{version}}
        rm -f /tmp/salmon.tgz
      when: salmon_bin.rc != 0



    - name: make modulesfile dir for salmon
      ansible.builtin.file:
        path: "{{modulefiles_dir}}/salmon"
        state: directory
        mode: '0755'        

    - name: write module file
      template: 
        src: templates/modules/salmon.j2
        dest: "{{modulefiles_dir}}/salmon/{{version}}"
        

        



        