- name: install samtools
  block:

    - name: Install samtools
      ansible.builtin.shell:  |
        curl -Lo /tmp/samtools.tgz.bz2 https://github.com/samtools/samtools/releases/download/1.13/samtools-1.13.tar.bz2 
        mkdir /tmp/samtools 
        tar jxvf /tmp/samtools.tgz.bz2 --strip 1 -C /tmp/samtools 
        cd /tmp/samtools 
        ./configure --prefix=/usr/software/samtools/1.13
        make  
        make install  
        rm -rf /tmp/samtools*
      loop:
        - 1.13
        - 1.12
        


    - name: make modules files for samtools