- name: install samtools
  block:

    - name: check if samtools executable is present
      shell: "which {{software_dir}}/samtools/{{item}}/bin/samtools"
      register: samtools_bin
      ignore_errors: true

    - name: Install samtools
      ansible.builtin.shell:  |
        curl -Lo /tmp/samtools.tgz.bz2 https://github.com/samtools/samtools/releases/download/{{item}}/samtools-{{item}}.tar.bz2 
        mkdir /tmp/samtools 
        tar jxvf /tmp/samtools.tgz.bz2 --strip 1 -C /tmp/samtools 
        cd /tmp/samtools 
        ./configure --prefix={{software_dir}}/samtools/{{item}}
        make  
        make install  
        rm -rf /tmp/samtools*
      when: samtools_bin.rc != 0


    - name: make modulesfile dir for samtools
        ansible.builtin.file:
          path: "{{modulefiles_dir}}/samtools"
          state: directory
          mode: '0755'        

    - name: write module file
      template: 
        src: templates/modules/samtools.j2
        dest: "{{modulefiles_dir}}/samtools/{{item}}"
        

  loop:
    - 1.13
    - 1.12
        



        