---
- name: install singularity

  block:

    - name: check if singularity executable is present
      shell: "which {{software_dir}}/singularity/{{version}}/bin/singularity"
      register: singularity_bin
      ignore_errors: true

    - name: install singularity build dependency packages
      package:
        name: 
        - build-essential
        - uuid-dev 
        - libgpgme-dev
        - squashfs-tools
        - libseccomp-dev
        - wget
        - pkg-config
        - git
        - cryptsetup-bin

    - name: get singularity repo
      ansible.builtin.shell:  |
        curl -Lo /tmp/singularity.tgz https://github.com/sylabs/singularity/releases/download/v{{version}}/singularity-ce-{{version}}.tar.gz
        mkdir /tmp/singularity
        tar jxvf /tmp/singularity.tar.bz2 --strip 1 -C /tmp/singularity
        cd /tmp/singularity
        ./mconfig 
        make -C ./builddir
        make -C ./builddir install
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin/"
      when: singularity_bin.rc != 0
    
    - name: make modulesfile dir for singularity
      ansible.builtin.file:
        path: "{{modulefiles_dir}}/singularity"
        state: directory
        mode: '0755'        

    - name: write module file
      template: 
        src: templates/modules/singularity.j2
        dest: "{{modulefiles_dir}}/singularity/{{version}}"
        

